name: 漏洞报告
description: 帮助我们修复漏洞
title: "[Bug] "
labels: ["Bug", "新请求"]
body:
- type: checkboxes
  id: "check"
  attributes:
    label: "检查项"
    description: "请逐个检查下列项目，并勾选确认。"
    options:
    - label: "我正在使用最新版本(包括测试版本)。"
      required: true
    - label: "我已在 [Issues 页面](https://github.com/MicGan6/Wallpaper-Engine-Tools/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。"
      required: true
- type: dropdown
  id: "user"
  attributes:
   label: 请选择你的身份
   multiple: false
   options:
     - "开发者"
     - "普通用户"
  validations:
    required: true
- type: input
  id: "Python-Ver"
  attributes:
    label: "请输入Python版本"
    placeholder: "e.g. 3.11.4"
- type: input
  id: "System-Version"
  attributes:
    label: 请输入操作系统版本
    placeholder: "e.g. Win11 23H2 Build 22631.4112"
- type: textarea
  id: "Bug-Behavior"
  attributes:
    label: 描述
    description: "详细描述该 Bug 的具体表现。"
  validations:
    required: true
- type: textarea
  id: "Bug"
  attributes:
    label: 重现步骤
    description: "详细描述要怎么操作才能触发这个 Bug。"
    value: |
      1、
      2、
  validations:
    required: true

- type: textarea
  id: "screenshots"
  attributes:
    label: 屏幕截图与附件
    description: "上传报错的屏幕截图，如有需要，请上传附件。"
    placeholder: "先点击这个文本框，然后再将文件直接拖拽到文本框中以上传。"
  validations:
    required: true