name: "新功能！"
description: "写出你想要的功能"
title: "[Future:]"
labels: ["Future", "新功能"]
body:
- type: checkboxes
  id : "Check"
  attributes:
    label: "检查项"
    description: "请检查以下项目，并勾选"
    options:
      - label: "我正在使用最新版本(包括测版本)"
        required: true
      - label: "我已在 [Issues 页面](https://github.com/MicGan6/Wallpaper-Engine-Tools/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。"
        required: true
      - label: "请不要给开发者难到变态的功能，开发者只有业余的时间来写程序, 如果你会Python，请自行PR，谢谢"
        required: true
- type: input
  id: "What"
  attributes:
    label: "请概括你要的功能"
- type: textarea
  id: "What2"
  attributes:
    label: "你想要的新功能(详细)"
- type: textarea
  id: "Why"
  attributes:
    label: "你为何要这个新功能"
    placeholder: "这个功能能带给我xxxxx的便利,如果没有，就xxxxxxxxx.......(后面请自行脑补)"