name: WPE-Tool 打包
on:
  push:
    branches:
    - main

jobs:
  Windows:
    if: contains(github.event.head_commit.message, '[不构建]') == false
    runs-on: windows-latest
    steps:
      - name: 结算仓库
        uses: actions/checkout@v2
      - name: 安装依赖
        run: pip install loguru
      - name: 编译程序
        run: |
          pip install pyinstaller
          pyinstaller main.spec
      - name: 复制资源文件
        run: |
          copy .\RePKG.exe .\dist\RePKG.exe
      - name: 上传打包项目
        uses: actions/upload-artifact@v4
        with:
          name: WPE-Tools
          path: .\dist\